<a href="https://colab.research.google.com/github/aymuos/masters-practise-repo/blob/main/MFDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment - 1 **

Q13 :

In this problem, we explore four fundamental subspaces of a matrix by using the MATLAB.
* Generate a random matrix A ∈ R

10×10 using MATLAB.
Check if the columns of A are linearly independent by determining its rank.
* Compute the null space of A using MATLAB verify that any vector in the null space satisfies
Av = 0.
* Compute the range space of A using MATLAB.
* Determine the rank of a matrix and dimension of null space of A by MATLAB. Verify rank
nullity Theorem.
* Generate any vector v ∈ R^10 and check if it lies in the null space or range space of A.

- Step 1 : Creating random 10*10 matrix

In [14]:
# Create a 10 * 10 matrix of random elements

import numpy as np

import random

# Generating a matrix of 100 random integers less than or equal to 20
mtrxA = np.random.randint(low=0,high=20, size =(10,10))


print(f'Given Matrix:  : {mtrxA}')
print(type(mtrxA))

Given Matrix:  : [[ 6 19  1  5  5 13 19  0  4 16]
 [ 6  6 16  7 13  4 12 14  2 13]
 [ 4 18 16 11 12 18  9  8 13 11]
 [ 2 11  0  3 10 19 18 13  1  8]
 [ 7 18  6  6  2  4  7 12 12  4]
 [17  8 19  4 16 12  2  4  0 17]
 [12 19 11  8  8 10 15 13 18 17]
 [ 9  4  3  0  3 13 18 18  8  9]
 [ 5  4  7  0 11  1  1 14 14 12]
 [12  2 14  3 18  0  9 16  4  3]]
<class 'numpy.ndarray'>


- Step 2 : Checking if columns of a are linearly independent by checking rank


In [15]:
# find rank of matrix

req_rank = np.linalg.matrix_rank(mtrxA)
print(f'Rank of the matrix is: {req_rank}')

Rank of the matrix is: 10


- Step 3 : Check for linear dependence

In [16]:
# check linear independence

if req_rank == mtrxA.shape[1]:  # number of vectors (columns)
    print("The columns are linearly independent.")
else:
    print("The columns are linearly dependent.")

The columns are linearly independent.


 - Step 4 :  Find linear independence

In [17]:
from scipy.linalg import null_space

null_space_mtrxA = null_space(mtrxA)

print(f'Null space of matrix A = {null_space_mtrxA}')

Null space of matrix A = []


In [18]:
# Final

# Create a 10 * 10 matrix of random elements

import numpy as np
from scipy.linalg import null_space
import random

# Generating a matrix of 100 random integers less than or equal to 20
mtrxA = np.random.randint(low=0,high=20, size =(10,10))


print(f'Given Matrix:  : {mtrxA}')
print(type(mtrxA))

# find rank of matrix

req_rank = np.linalg.matrix_rank(mtrxA)
print(f'Rank of the matrix is: {req_rank}')
# check linear independence

if req_rank == mtrxA.shape[1]:  # number of vectors (columns)
    print("The columns are linearly independent. Thus Full Rank")
else:
    print("The columns are linearly dependent.")

null_space_mtrxA = null_space(mtrxA)

print(f'Null space of matrix A = {null_space_mtrxA}')


Given Matrix:  : [[19  2 14  9 14 17  3  8  9 17]
 [15  6 14  5  3  4  1  7 13 14]
 [ 0 12  2 18 18  6 16  4  4 16]
 [ 8 11  1 14  8 13 15  3  2 16]
 [ 2 17  1  3  8 16 15 14 15 10]
 [ 5  7  8  2  1  0  4  8 18  3]
 [ 3 16  4 16  7 16  2 16  8 14]
 [ 8 14  7  9  3  8 18 12 15  5]
 [ 3 11 12  5  8 14 11 10 14  7]
 [11  5  2  1  2  6 16 11  0  6]]
<class 'numpy.ndarray'>
Rank of the matrix is: 10
The columns are linearly independent.
Null space of matrix A = []
