<a href="https://colab.research.google.com/github/aymuos/masters-practise-repo/blob/main/MFDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment - 1 **

Q13 :

In this problem, we explore four fundamental subspaces of a matrix by using the MATLAB.
* Generate a random matrix A ∈ R

10×10 using MATLAB.
Check if the columns of A are linearly independent by determining its rank.
* Compute the null space of A using MATLAB verify that any vector in the null space satisfies
Av = 0.
* Compute the range space of A using MATLAB.
* Determine the rank of a matrix and dimension of null space of A by MATLAB. Verify rank
nullity Theorem.
* Generate any vector v ∈ R^10 and check if it lies in the null space or range space of A.

- Step 1 : Creating random 10*10 matrix

In [2]:
# Create a 10 * 10 matrix of random elements

import numpy as np

import random
from scipy.linalg import orth


# Generating a matrix of 7 * 10 random integers less than or equal to 20
mtrxA_part = np.random.randint(low=0,high=20, size =(7,10))
print(f'Print part Matrix:  : \n{mtrxA_part}\n')

# purposefully making the others linearly dependent

mtrxA = np.vstack([
    mtrxA_part,
    mtrxA_part[0] + mtrxA_part[1],   # Row 8 as sum of rows 1 and 2
    2 * mtrxA_part[2] - mtrxA_part[3],  # Row 9 as a linear combination of rows 3 and 4
    mtrxA_part[4] - mtrxA_part[5]      # Row 10 as a difference of rows 5 and 6
])

print(f'Final 10 * 10 Matrix:  :\n{mtrxA}\n')
print(type(mtrxA))

Print part Matrix:  : 
[[19 14  2 11  7 18 18  0 19 10]
 [ 3  2 15  7 17 12  7 18  6  5]
 [18 14  1  0 10  1  4 15  1  2]
 [16  8 10 11 10 12 10 12 16 18]
 [13  9  0  1 13  6 17  8  3 13]
 [ 4 14 15 19  8 14 15  7  2  7]
 [ 3 10 18  4  5 11  9 19  6 12]]

Final 10 * 10 Matrix:  :
[[ 19  14   2  11   7  18  18   0  19  10]
 [  3   2  15   7  17  12   7  18   6   5]
 [ 18  14   1   0  10   1   4  15   1   2]
 [ 16   8  10  11  10  12  10  12  16  18]
 [ 13   9   0   1  13   6  17   8   3  13]
 [  4  14  15  19   8  14  15   7   2   7]
 [  3  10  18   4   5  11   9  19   6  12]
 [ 22  16  17  18  24  30  25  18  25  15]
 [ 20  20  -8 -11  10 -10  -2  18 -14 -14]
 [  9  -5 -15 -18   5  -8   2   1   1   6]]

<class 'numpy.ndarray'>


- Step 2 : Checking if columns of a are linearly independent by checking rank


In [3]:
# find rank of matrix

req_rank = np.linalg.matrix_rank(mtrxA)
print(f'Rank of the matrix is: {req_rank}')

Rank of the matrix is: 7


- Step 3 : Check for linear dependence

In [4]:
# check linear independence

if req_rank == mtrxA.shape[1]:  # number of vectors (columns)
    print("The columns are linearly independent.")
else:
    print("The columns are linearly dependent.")

The columns are linearly dependent.


 - Step 4 :  Find linear independence

In [5]:
from scipy.linalg import null_space

null_space_mtrxA = null_space(mtrxA)

print(f'Null space of matrix A = \n {null_space_mtrxA}')

Null space of matrix A = 
 [[ 0.5482948  -0.04861413 -0.16088932]
 [-0.52338295 -0.17948295 -0.11515569]
 [ 0.26439699  0.00947288 -0.64018432]
 [-0.03246913  0.21666973  0.29010883]
 [-0.33277929 -0.18873365 -0.26744907]
 [ 0.22241589 -0.58345009  0.35812502]
 [ 0.19224015  0.50668927 -0.01325337]
 [ 0.01033254  0.27083572  0.50129927]
 [-0.37654705  0.35269752 -0.1120434 ]
 [-0.1241833  -0.29643057  0.05515267]]


Step 5 : Verify Ax= 0

In [6]:
# Verify that each vector in the null space satisfies A * v = 0
if null_space_mtrxA.size > 0:
    for i in range(null_space_mtrxA.shape[1]):
        v = null_space_mtrxA[:, i]
        result = mtrxA @ v   # matrix multiplication operator , introduced in py 3.5
        print(f"\nChecking vector {i+1} in the null space:")
        print("Vector v:", v)
        print("A * v:", result)
        print("Is Av = 0?", np.allclose(result, 0))
else:
    print("The matrix has no null space vectors (it's full rank).")


Checking vector 1 in the null space:
Vector v: [ 0.5482948  -0.52338295  0.26439699 -0.03246913 -0.33277929  0.22241589
  0.19224015  0.01033254 -0.37654705 -0.1241833 ]
A * v: [-3.55271368e-15  1.77635684e-15 -8.65973959e-15 -3.55271368e-15
 -3.55271368e-15  3.99680289e-15  7.10542736e-15 -3.55271368e-15
 -1.15463195e-14 -8.21565038e-15]
Is Av = 0? True

Checking vector 2 in the null space:
Vector v: [-0.04861413 -0.17948295  0.00947288  0.21666973 -0.18873365 -0.58345009
  0.50668927  0.27083572  0.35269752 -0.29643057]
A * v: [ 2.66453526e-15 -5.55111512e-15 -1.11022302e-16  0.00000000e+00
 -8.88178420e-16 -1.55431223e-15 -6.66133815e-16 -5.32907052e-15
  6.66133815e-16  4.44089210e-16]
Is Av = 0? True

Checking vector 3 in the null space:
Vector v: [-0.16088932 -0.11515569 -0.64018432  0.29010883 -0.26744907  0.35812502
 -0.01325337  0.50129927 -0.1120434   0.05515267]
A * v: [ 2.22044605e-15  4.99600361e-16  1.70696790e-15  2.44249065e-15
 -2.22044605e-16  4.99600361e-16  4.94049

Step 6 : Finding range space

In [7]:
# Compute the orthonormal basis for the range space (column space) of matrix A
range_space_mtrxA = orth(mtrxA)

print(f'Range space (column space) of matrix A:\n{range_space_mtrxA}\n')

print(' ----------- ANSWER -----------')

# Verification: Checking if each basis vector is indeed in the range of A
for i in range(range_space_mtrxA.shape[1]):
    basis_vector = range_space_mtrxA[:, i]
    print(f"Basis vector {i+1}:", basis_vector)
    # Check if this vector is in the span of columns of A
    # This should hold since orth() finds an orthonormal basis for the column space of A
    print("Is this a column combination of A?", np.allclose(mtrxA @ np.linalg.lstsq(mtrxA, basis_vector, rcond=None)[0], basis_vector))

Range space (column space) of matrix A:
[[-0.35678338 -0.04622362  0.44719614 -0.46133132 -0.04866127 -0.15462365
  -0.31328628]
 [-0.270756   -0.02072007 -0.34332444  0.44593592 -0.39144251  0.32631884
   0.12840088]
 [-0.19563419  0.39199123 -0.06296767 -0.0341167  -0.00566359 -0.26496765
   0.25697211]
 [-0.35771606 -0.03737381  0.15132735  0.18215497  0.08660071 -0.52325402
   0.60547577]
 [-0.25114883  0.18137843  0.2310561   0.11943568  0.52193797  0.46963115
   0.10034111]
 [-0.30597709 -0.14679578 -0.31437268 -0.34619465  0.43424428  0.31885873
   0.20633901]
 [-0.2802285  -0.03357257 -0.34337364  0.37431486  0.40609649 -0.38874724
  -0.58846328]
 [-0.62753938 -0.0669437   0.1038717  -0.0153954  -0.44010378  0.1716952
  -0.1848854 ]
 [-0.03355232  0.82135626 -0.27726268 -0.25038837 -0.09792789 -0.00668128
  -0.09153154]
 [ 0.05482827  0.32817421  0.54542878  0.46563033  0.08769369  0.15077242
  -0.1059979 ]]

 ----------- ANSWER -----------
Basis vector 1: [-0.35678338 -0.27075

- Step 7 : Verifying rank nullity theorem

In [8]:
rank_A = np.linalg.matrix_rank(mtrxA)
print(f'Rank of matrix A: {rank_A}')

# Step 2: Compute the null space of A and determine its dimension
null_space_A = null_space(mtrxA)
nullity_A = null_space_A.shape[1]  # Number of basis vectors in the null space
print(f'Nullity of matrix A (dimension of the null space): {nullity_A}')

# Step 3: Verify the Rank-Nullity Theorem
num_columns = mtrxA.shape[1]
rank_nullity_sum = rank_A + nullity_A
print(f'Sum of Rank and Nullity: {rank_nullity_sum}')
print(f'Number of columns in A: {num_columns}')
print("Rank-Nullity Theorem holds:", rank_nullity_sum == num_columns)

Rank of matrix A: 7
Nullity of matrix A (dimension of the null space): 3
Sum of Rank and Nullity: 10
Number of columns in A: 10
Rank-Nullity Theorem holds: True


- Step 8 : Generate random vector of dim 10 and check if it lies in the null space

In [12]:
v = np.random.rand(10)
print(f"Random vector v:\n{v}\n")

# Check if v lies in the null space of A
result_null_space = mtrxA @ v   # calculating Av
is_in_null_space = np.allclose(result_null_space, 0)   # checks if elementwise equal to 0
print(f"Is v in the null space of A? {is_in_null_space}")

# Check if v lies in the range space of A
# Solves the equation Ax = v and check if a solution exists
try:
    # Solves for x in Ax = v
    x = np.linalg.lstsq(mtrxA, v, rcond=None)[0]  # least square solution
    # Check if A * x is approximately equal to v
    is_in_range_space = np.allclose(mtrxA @ x, v)
    print(f"Is v in the range space of A? {is_in_range_space}")
except np.linalg.LinAlgError:
    print("No solution exists; v is not in the range space of A.")

Random vector v:
[0.87681177 0.51476879 0.36387197 0.44069966 0.30313874 0.59509211
 0.56137096 0.1055619  0.23137392 0.38613815]

Is v in the null space of A? False
Is v in the range space of A? False


In [18]:
# # Final

# # Create a 10 * 10 matrix of random elements

# import numpy as np
# from scipy.linalg import null_space , ortho
# import random

# # Generating a matrix of 100 random integers less than or equal to 20
# mtrxA = np.random.randint(low=0,high=20, size =(10,10))


# print(f'Given Matrix:  : {mtrxA}')
# print(type(mtrxA))

# # find rank of matrix

# req_rank = np.linalg.matrix_rank(mtrxA)
# print(f'Rank of the matrix is: {req_rank}')
# # check linear independence

# if req_rank == mtrxA.shape[1]:  # number of vectors (columns)
#     print("The columns are linearly independent. Thus Full Rank")
# else:
#     print("The columns are linearly dependent.")

# null_space_mtrxA = null_space(mtrxA)

# print(f'Null space of matrix A = {null_space_mtrxA}')


Given Matrix:  : [[19  2 14  9 14 17  3  8  9 17]
 [15  6 14  5  3  4  1  7 13 14]
 [ 0 12  2 18 18  6 16  4  4 16]
 [ 8 11  1 14  8 13 15  3  2 16]
 [ 2 17  1  3  8 16 15 14 15 10]
 [ 5  7  8  2  1  0  4  8 18  3]
 [ 3 16  4 16  7 16  2 16  8 14]
 [ 8 14  7  9  3  8 18 12 15  5]
 [ 3 11 12  5  8 14 11 10 14  7]
 [11  5  2  1  2  6 16 11  0  6]]
<class 'numpy.ndarray'>
Rank of the matrix is: 10
The columns are linearly independent.
Null space of matrix A = []


 ------------------------------------------------------------------------------------------------------------------------------------------

 # 2nd Question
 -----------------------------------------------------------------------

 In this problem, we explore Linear regression by using MATLAB.
* Generate 50 data points (xi, yi) by using the following equation
yi = 3xi + 2 + ui , with xi is an uniformly distributed random variable between (−10, 10) and ui is a normal random variable with zero mean and unit standard deviation.
* For the data generated in the above question solve a least square problem to fit a linear model yi = axi + b.

* Find out the output yi for each training data xi by using the linear model. Then compute the
minimum least squared error (MSE).

In [13]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Step 1: Generate 50 data points
np.random.seed(0)  # For reproducibility

# Generate x values uniformly distributed between -10 and 10
x = np.random.uniform(-10, 10, 50)

print(f'Generated uniformly distributed values are:\n {x} \n')

# Generate u values from a normal distribution with mean 0 and standard deviation 1
u = np.random.normal(0, 1, 50)
print(f'Generated normally distributed values are:\n {x} \n')
# Calculate y using the given equation y = 3x + 2 + u
y = 3 * x + 2 + u

# Reshape x to fit the model (50, 1) because sklearn expects a 2D array for input features
x = x.reshape(-1, 1)

# Step 2: Fit a linear regression model y = ax + b
model = LinearRegression()
model.fit(x, y)

# Extract coefficients a and b
a = model.coef_[0]
b = model.intercept_
print(f"Fitted model: y = {a:.2f}x + {b:.2f}")  # 2 decimal places

# Step 3: Predict y values using the fitted model
y_pred = model.predict(x)

# Calculate Mean Squared Error
mse = mean_squared_error(y, y_pred)
print(f"Mean Squared Error (MSE): {mse:.2f}")


Values generated are:
 [ 0.97627008  4.30378733  2.05526752  0.89766366 -1.52690401  2.91788226
 -1.24825577  7.83546002  9.27325521 -2.33116962  5.83450076  0.5778984
  1.36089122  8.51193277 -8.57927884 -8.25741401 -9.59563205  6.65239691
  5.56313502  7.40024296  9.57236684  5.98317128 -0.77041275  5.61058353
 -7.63451148  2.79842043 -7.13293425  8.89337834  0.43696644 -1.7067612
 -4.70888776  5.48467379 -0.87699336  1.36867898 -9.62420399  2.35270994
  2.24191445  2.33867994  8.87496157  3.63640598 -2.80984199 -1.25936092
  3.95262392 -8.79549057  3.33533431  3.41275739 -5.79234878 -7.42147405
 -3.69143298 -2.72578458] 

Fitted model: y = 2.98x + 1.84
Mean Squared Error (MSE): 0.86
