<a href="https://colab.research.google.com/github/aymuos/masters-practise-repo/blob/main/MFDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment - 1 **

Q13 :

In this problem, we explore four fundamental subspaces of a matrix by using the MATLAB.
* Generate a random matrix A ∈ R

10×10 using MATLAB.
Check if the columns of A are linearly independent by determining its rank.
* Compute the null space of A using MATLAB verify that any vector in the null space satisfies
Av = 0.
* Compute the range space of A using MATLAB.
* Determine the rank of a matrix and dimension of null space of A by MATLAB. Verify rank
nullity Theorem.
* Generate any vector v ∈ R^10 and check if it lies in the null space or range space of A.

- Step 1 : Creating random 10*10 matrix

In [21]:
# Create a 10 * 10 matrix of random elements

import numpy as np

import random

# Generating a matrix of 7 * 10 random integers less than or equal to 20
mtrxA_part = np.random.randint(low=0,high=20, size =(7,10))
print(f'Print part Matrix:  : \n{mtrxA_part}\n')

# purposefully making the others linearly dependent

mtrxA = np.vstack([
    mtrxA_part,
    mtrxA_part[0] + mtrxA_part[1],   # Row 8 as sum of rows 1 and 2
    2 * mtrxA_part[2] - mtrxA_part[3],  # Row 9 as a linear combination of rows 3 and 4
    mtrxA_part[4] - mtrxA_part[5]      # Row 10 as a difference of rows 5 and 6
])

print(f'Final 10 * 10 Matrix:  :\n{mtrxA}\n')
print(type(mtrxA))

Print part Matrix:  : 
[[ 7 19 16 14  8 11  6 16  6 14]
 [15  9 10  5 17  0 13  5  7 12]
 [ 7 11  1 14 11 16 13  6  7  6]
 [ 0  3  8  4  0  7  4  5  0  8]
 [11 11 18  1  5  6  1  5 19 15]
 [ 6 15 14  6 13 15  3  9 15 16]
 [ 6 10 16 13 15 17  2  5  0  4]]

Given Matrix:  :
[[ 7 19 16 14  8 11  6 16  6 14]
 [15  9 10  5 17  0 13  5  7 12]
 [ 7 11  1 14 11 16 13  6  7  6]
 [ 0  3  8  4  0  7  4  5  0  8]
 [11 11 18  1  5  6  1  5 19 15]
 [ 6 15 14  6 13 15  3  9 15 16]
 [ 6 10 16 13 15 17  2  5  0  4]
 [22 28 26 19 25 11 19 21 13 26]
 [14 19 -6 24 22 25 22  7 14  4]
 [ 5 -4  4 -5 -8 -9 -2 -4  4 -1]]

<class 'numpy.ndarray'>


- Step 2 : Checking if columns of a are linearly independent by checking rank


In [15]:
# find rank of matrix

req_rank = np.linalg.matrix_rank(mtrxA)
print(f'Rank of the matrix is: {req_rank}')

Rank of the matrix is: 10


- Step 3 : Check for linear dependence

In [16]:
# check linear independence

if req_rank == mtrxA.shape[1]:  # number of vectors (columns)
    print("The columns are linearly independent.")
else:
    print("The columns are linearly dependent.")

The columns are linearly independent.


 - Step 4 :  Find linear independence

In [17]:
from scipy.linalg import null_space

null_space_mtrxA = null_space(mtrxA)

print(f'Null space of matrix A = {null_space_mtrxA}')

Null space of matrix A = []


In [18]:
# Final

# Create a 10 * 10 matrix of random elements

import numpy as np
from scipy.linalg import null_space
import random

# Generating a matrix of 100 random integers less than or equal to 20
mtrxA = np.random.randint(low=0,high=20, size =(10,10))


print(f'Given Matrix:  : {mtrxA}')
print(type(mtrxA))

# find rank of matrix

req_rank = np.linalg.matrix_rank(mtrxA)
print(f'Rank of the matrix is: {req_rank}')
# check linear independence

if req_rank == mtrxA.shape[1]:  # number of vectors (columns)
    print("The columns are linearly independent. Thus Full Rank")
else:
    print("The columns are linearly dependent.")

null_space_mtrxA = null_space(mtrxA)

print(f'Null space of matrix A = {null_space_mtrxA}')


Given Matrix:  : [[19  2 14  9 14 17  3  8  9 17]
 [15  6 14  5  3  4  1  7 13 14]
 [ 0 12  2 18 18  6 16  4  4 16]
 [ 8 11  1 14  8 13 15  3  2 16]
 [ 2 17  1  3  8 16 15 14 15 10]
 [ 5  7  8  2  1  0  4  8 18  3]
 [ 3 16  4 16  7 16  2 16  8 14]
 [ 8 14  7  9  3  8 18 12 15  5]
 [ 3 11 12  5  8 14 11 10 14  7]
 [11  5  2  1  2  6 16 11  0  6]]
<class 'numpy.ndarray'>
Rank of the matrix is: 10
The columns are linearly independent.
Null space of matrix A = []
