<a href="https://colab.research.google.com/github/aymuos/masters-practise-repo/blob/main/MFDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment - 1 **

Q13 :

In this problem, we explore four fundamental subspaces of a matrix by using the MATLAB.
* Generate a random matrix A ∈ R

10×10 using MATLAB.
Check if the columns of A are linearly independent by determining its rank.
* Compute the null space of A using MATLAB verify that any vector in the null space satisfies
Av = 0.
* Compute the range space of A using MATLAB.
* Determine the rank of a matrix and dimension of null space of A by MATLAB. Verify rank
nullity Theorem.
* Generate any vector v ∈ R^10 and check if it lies in the null space or range space of A.

- Step 1 : Creating random 10*10 matrix

In [28]:
# Create a 10 * 10 matrix of random elements

import numpy as np

import random
from scipy.linalg import orth


# Generating a matrix of 7 * 10 random integers less than or equal to 20
mtrxA_part = np.random.randint(low=0,high=20, size =(7,10))
print(f'Print part Matrix:  : \n{mtrxA_part}\n')

# purposefully making the others linearly dependent

mtrxA = np.vstack([
    mtrxA_part,
    mtrxA_part[0] + mtrxA_part[1],   # Row 8 as sum of rows 1 and 2
    2 * mtrxA_part[2] - mtrxA_part[3],  # Row 9 as a linear combination of rows 3 and 4
    mtrxA_part[4] - mtrxA_part[5]      # Row 10 as a difference of rows 5 and 6
])

print(f'Final 10 * 10 Matrix:  :\n{mtrxA}\n')
print(type(mtrxA))

Print part Matrix:  : 
[[ 4 13 10  7 15 13  9  5 14  9]
 [14 19 11  4  9  1  7 19 16 15]
 [ 4 13 16 10 13  4 13  3  5 11]
 [ 9 16 10 13  7  9 17  7 12  1]
 [18  1  2 16 12  6  9 15  1 10]
 [ 0 10 19 12 18  0 11  1 12 13]
 [ 3 19 10  1 10 10  7  5  4  0]]

Final 10 * 10 Matrix:  :
[[  4  13  10   7  15  13   9   5  14   9]
 [ 14  19  11   4   9   1   7  19  16  15]
 [  4  13  16  10  13   4  13   3   5  11]
 [  9  16  10  13   7   9  17   7  12   1]
 [ 18   1   2  16  12   6   9  15   1  10]
 [  0  10  19  12  18   0  11   1  12  13]
 [  3  19  10   1  10  10   7   5   4   0]
 [ 18  32  21  11  24  14  16  24  30  24]
 [ -1  10  22   7  19  -1   9  -1  -2  21]
 [ 18  -9 -17   4  -6   6  -2  14 -11  -3]]

<class 'numpy.ndarray'>


- Step 2 : Checking if columns of a are linearly independent by checking rank


In [29]:
# find rank of matrix

req_rank = np.linalg.matrix_rank(mtrxA)
print(f'Rank of the matrix is: {req_rank}')

Rank of the matrix is: 7


- Step 3 : Check for linear dependence

In [30]:
# check linear independence

if req_rank == mtrxA.shape[1]:  # number of vectors (columns)
    print("The columns are linearly independent.")
else:
    print("The columns are linearly dependent.")

The columns are linearly dependent.


 - Step 4 :  Find linear independence

In [31]:
from scipy.linalg import null_space

null_space_mtrxA = null_space(mtrxA)

print(f'Null space of matrix A = \n {null_space_mtrxA}')

Null space of matrix A = 
 [[ 6.77103374e-01  4.04592116e-02 -2.77394873e-01]
 [-2.22957119e-01 -1.82264266e-01 -4.40446413e-01]
 [ 2.73086120e-01  6.31492058e-01  2.49114422e-01]
 [-4.25948159e-01  2.39797326e-01 -4.05930691e-01]
 [ 1.30563365e-01 -3.91216804e-01  5.00347267e-02]
 [-3.42006363e-02  3.31282786e-01  8.64111465e-02]
 [ 6.75444586e-02 -4.71032784e-01  4.62933290e-01]
 [-4.12054218e-01  1.36437806e-01  5.06802497e-01]
 [ 1.30948670e-01  3.26533926e-04 -5.88782734e-03]
 [-1.61549741e-01 -7.46436526e-02 -1.45121648e-01]]


Step 5 : Verify Ax= 0

In [32]:
# Verify that each vector in the null space satisfies A * v = 0
if null_space_mtrxA.size > 0:
    for i in range(null_space_mtrxA.shape[1]):
        v = null_space_mtrxA[:, i]
        result = mtrxA @ v
        print(f"\nChecking vector {i+1} in the null space:")
        print("Vector v:", v)
        print("A * v:", result)
        print("Is Av = 0?", np.allclose(result, 0))
else:
    print("The matrix has no null space vectors (it's full rank).")


Checking vector 1 in the null space:
Vector v: [ 0.67710337 -0.22295712  0.27308612 -0.42594816  0.13056337 -0.03420064
  0.06754446 -0.41205422  0.13094867 -0.16154974]
A * v: [ 1.04360964e-14 -8.88178420e-16  6.43929354e-15  4.21884749e-15
 -3.33066907e-15  7.54951657e-15  1.77635684e-15  9.76996262e-15
  5.77315973e-15 -1.17683641e-14]
Is Av = 0? True

Checking vector 2 in the null space:
Vector v: [ 4.04592116e-02 -1.82264266e-01  6.31492058e-01  2.39797326e-01
 -3.91216804e-01  3.31282786e-01 -4.71032784e-01  1.36437806e-01
  3.26533926e-04 -7.46436526e-02]
A * v: [ 4.32986980e-15  0.00000000e+00 -1.11022302e-15 -2.55351296e-15
 -4.44089210e-15  1.33226763e-15  2.77555756e-17  4.44089210e-15
  1.11022302e-15 -4.35762537e-15]
Is Av = 0? True

Checking vector 3 in the null space:
Vector v: [-0.27739487 -0.44044641  0.24911442 -0.40593069  0.05003473  0.08641115
  0.46293329  0.5068025  -0.00588783 -0.14512165]
A * v: [-4.21884749e-15  6.66133815e-15  1.11022302e-15  3.60822483e-16


Step 6 : Finding range space

In [33]:
# Compute the orthonormal basis for the range space (column space) of matrix A
range_space_mtrxA = orth(mtrxA)

print(f'Range space (column space) of matrix A:\n{range_space_mtrxA}\n')

print(' ----------- ANSWER -----------')

# Verification: Checking if each basis vector is indeed in the range of A
for i in range(range_space_mtrxA.shape[1]):
    basis_vector = range_space_mtrxA[:, i]
    print(f"Basis vector {i+1}:", basis_vector)
    # Check if this vector is in the span of columns of A
    # This should hold since orth() finds an orthonormal basis for the column space of A
    print("Is this a column combination of A?", np.allclose(mtrxA @ np.linalg.lstsq(mtrxA, basis_vector, rcond=None)[0], basis_vector))

Range space (column space) of matrix A:
[[-0.28534637  0.0255354   0.11386115  0.23164331  0.05052384  0.67966594
   0.23123717]
 [-0.33745048 -0.20335258  0.18443779 -0.51958175 -0.01873792 -0.44585342
  -0.09122877]
 [-0.27571823  0.14114498 -0.21146136  0.21524355 -0.08618463 -0.24742179
   0.27874695]
 [-0.2798686  -0.10647016  0.14744186  0.61257603  0.24089187 -0.45956718
   0.27830133]
 [-0.2215241  -0.41251688 -0.51849896  0.10776374  0.17560609  0.08196665
  -0.35974065]
 [-0.29962085  0.28733023 -0.23483286  0.05001855  0.42650503  0.02551251
  -0.50411268]
 [-0.20925567  0.03833654  0.26040588  0.34825665 -0.69580898 -0.01949855
  -0.53020574]
 [-0.62279685 -0.17781718  0.29829894 -0.28793845  0.03178592  0.23381252
   0.14000841]
 [-0.27156787  0.38876012 -0.57036457 -0.18208893 -0.41326112 -0.03527639
   0.27919257]
 [ 0.07809675 -0.6998471  -0.2836661   0.05774519 -0.25089894  0.05645415
   0.14437203]]

Basis vector 1: [-0.28534637 -0.33745048 -0.27571823 -0.2798686  -0.

In [18]:
# Final

# Create a 10 * 10 matrix of random elements

import numpy as np
from scipy.linalg import null_space , ortho
import random

# Generating a matrix of 100 random integers less than or equal to 20
mtrxA = np.random.randint(low=0,high=20, size =(10,10))


print(f'Given Matrix:  : {mtrxA}')
print(type(mtrxA))

# find rank of matrix

req_rank = np.linalg.matrix_rank(mtrxA)
print(f'Rank of the matrix is: {req_rank}')
# check linear independence

if req_rank == mtrxA.shape[1]:  # number of vectors (columns)
    print("The columns are linearly independent. Thus Full Rank")
else:
    print("The columns are linearly dependent.")

null_space_mtrxA = null_space(mtrxA)

print(f'Null space of matrix A = {null_space_mtrxA}')


Given Matrix:  : [[19  2 14  9 14 17  3  8  9 17]
 [15  6 14  5  3  4  1  7 13 14]
 [ 0 12  2 18 18  6 16  4  4 16]
 [ 8 11  1 14  8 13 15  3  2 16]
 [ 2 17  1  3  8 16 15 14 15 10]
 [ 5  7  8  2  1  0  4  8 18  3]
 [ 3 16  4 16  7 16  2 16  8 14]
 [ 8 14  7  9  3  8 18 12 15  5]
 [ 3 11 12  5  8 14 11 10 14  7]
 [11  5  2  1  2  6 16 11  0  6]]
<class 'numpy.ndarray'>
Rank of the matrix is: 10
The columns are linearly independent.
Null space of matrix A = []
